apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "promtail.fullname" . }}-config
  labels:
    {{- include "promtail.labels" . | nindent 4 }}
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: {{ .Values.loki.url }}

    scrape_configs:
      - job_name: system
        static_configs:
        {{- range .Values.logPaths }}
          - targets:
              - localhost
            labels:
              {{- range $key, $value := .labels }}
              {{ $key }}: {{ $value | quote }}
              {{- end }}
              __path__: {{ .path | quote }}
        {{- end }}
