{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "promtail.fullname" . }}
  labels:
    release: {{ .Release.Name }}
    {{- include "promtail.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ include "promtail.name" . }}
  endpoints:
    - port: http
      interval: 15s
{{- end }}
