apiVersion: v1
kind: Service
metadata:
  name: loki
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3100
      protocol: TCP
      name: http
  selector:
    app: loki
