replicaCount: 1

image:
  repository: grafana/loki
  tag: 2.9.4
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3100

persistence:
  enabled: true
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  size: 10Gi

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

lokiConfig:
  schema_version: "v11"
  storage:
    type: filesystem
    filesystem:
      directory: /var/loki/chunks
  chunk_store_config:
    max_look_back_period: 0s
  table_manager:
    retention_deletes_enabled: true
    retention_period: 168h
  compactor:
    working_directory: /var/loki/compactor
  limits_config:
    retention_period: 168h
